back/back/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import login
from django.views.static import serve
from . import settings


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'back.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}),
    url(r'^marks/', include('marks.urls', namespace="marks")),
    url(r'^$', 'back.views.index'),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'accounts/login.html'}),
    url(r'^accounts/logout/$', "back.views.logout_view")
)

back/marks/urls.py
__author__ = 'Steven'


from django.conf.urls import url


from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^myprojects$', views.myprojects, name='myprojects'),
    url(r'^(?P<project_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<project_id>[0-9]+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<project_id>[0-9]+)/editsec/$', views.editsec, name='editsec'),
    url(r'^(?P<project_id>[0-9]+)/deleteimg/(?P<pict_id>[0-9]+)/$', views.deleteimg, name='deleteimg'),
    # ex: /polls/5/mark/
    url(r'^(?P<project_id>[0-9]+)/mark/$', views.mark, name='grade'),
]

back/marks/models.py
from django.db import models
from django.contrib.auth.models import User

import datetime

class Picture(models.Model):
    #data = models.BinaryField()
    file = models.ImageField(upload_to="picture/%Y/%m/%d", max_length=150)
    title = models.CharField(max_length=50)

    def __str__(self):
        return "%s - %s " % (self.title, str(self.file))

class Timeslot(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Project(models.Model):

    name = models.CharField(max_length=100)
    description = models.TextField()
    members = models.ManyToManyField(User)
    #picture_cover = models.ForeignKey(Picture, null=True)
    pictures = models.ManyToManyField(Picture, blank=True)
    timeslot = models.ForeignKey(Timeslot, blank=True)
    marks = models.ManyToManyField(User, through='Mark', related_name="project_marks_student")

    def __str__(self):
        return self.name

class Question(models.Model):
    title = models.CharField(max_length=200)
    detail = models.CharField(max_length=250, blank=True)

    def __str__(self):
        return self.title

class Mark(models.Model):
    student = models.ForeignKey(User)
    project = models.ForeignKey(Project)
    question = models.ForeignKey(Question)
    result = models.IntegerField()
    created     = models.DateTimeField(editable=False)
    modified    = models.DateTimeField()

    def __str__(self):
        return "Mark(%s) by %s for %s" % (self.result, self.student, self.question)

    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        if not self.id:
            self.created = datetime.datetime.today()
        self.modified = datetime.datetime.today()
        return super(Mark, self).save(*args, **kwargs)

back/marks/forms.py
__author__ = 'Steven'


from django import forms

#class UploadFileForm(forms.Form):
#    title = forms.CharField(max_length=50)
#    file = forms.FileField()

from django.forms import ModelForm

from .models import Picture, Project

class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'description']


class PictureForm(ModelForm):
     class Meta:
         model = Picture

back/marks/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.contrib.auth import logout


from .models import Project, Question, Mark, Picture
from .forms import PictureForm, ProjectForm
from django.core.exceptions import PermissionDenied

@login_required
def index(request):
    l = []
    all_list = Project.objects.all() # shared timeslot only
    timeslots = list(set([proj.timeslot for proj in Project.objects.filter(members=request.user)]))
    for proj in all_list:
        if proj.timeslot in timeslots:
            l.append(proj)
    projects_rated = list(set([m.project for m in Mark.objects.filter(student=request.user)]))
    if request.user.is_staff:
        l = all_list
    context = {'list': l, 'projects_rated': projects_rated}
    return render(request, 'marks/index.html', context)

@login_required
def myprojects(request):
    my_projects = []
    if request.user.is_authenticated():
        my_projects = Project.objects.filter(members=request.user)

    context = {'my_projects': my_projects}
    return render(request, 'marks/myprojects.html', context)


@login_required
def detail(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    questions_raw = Question.objects.all()
    marks = Mark.objects.filter(student=request.user, project=project)
    questions = []
    entirely_marked = True
    for q in questions_raw:
        value = None
        for m in marks:
            if q.pk == m.question.pk:
                value = m.result
        if entirely_marked and not value:
            entirely_marked = False
        questions.append((q, value))
    shared_timeslot = False
    for proj in Project.objects.filter(members=request.user):
        if not shared_timeslot and project.timeslot == proj.timeslot:
            shared_timeslot = True
    context = {'project': project, 'questions': questions, "shared_timeslot": shared_timeslot,
               'entirely_marked': entirely_marked}
    return render(request, 'marks/project.html', context)

@login_required
def deleteimg(request, project_id, pict_id):
    project = get_object_or_404(Project, pk=project_id)
    if request.user not in project.members.all():
        raise PermissionDenied
    pict = get_object_or_404(Picture, pk=pict_id)
    pict.delete()
    return HttpResponseRedirect(reverse('marks:detail', args=(project.id,)))


@login_required
def editsec(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    if request.user not in project.members.all():
        raise PermissionDenied
    if request.method == 'POST':

        form = ProjectForm(request.POST, instance=project)
        if form.is_valid():
            proj = form.save()
            #proj.save()
            return HttpResponseRedirect(reverse('marks:detail', args=(project.id,)))
    else:
        form = ProjectForm(instance=project)
    return render(request, 'marks/project.html', {'form': form, 'project':project})


@login_required
def edit(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    if request.user not in project.members.all():
        raise PermissionDenied
    if request.method == 'POST':

        form = PictureForm(request.POST, request.FILES)
        if form.is_valid():
            pict = form.save()
            project.pictures.add(pict)
            #instance = Picture(file=request.FILES['file'])
            #instance.set_title(form.title)
            #instance.save()
            return HttpResponseRedirect(reverse('marks:detail', args=(project.id,)))
    else:
        form = PictureForm()
    return render(request, 'marks/project.html', {'form_pict': form, 'project':project})

@login_required
def mark(request, project_id):
    p = get_object_or_404(Project, pk=project_id)
    if request.user in p.members.all():
        raise PermissionDenied
    shared_timeslot = False
    for proj in Project.objects.filter(members=request.user):
        if not shared_timeslot and p.timeslot == proj.timeslot:
            shared_timeslot = True
    if not shared_timeslot:
        raise PermissionDenied
    for key, value in request.POST.items():
        if key.startswith("question-"):
            try:
                quest = Question.objects.get(pk=int(key[9:]))
                ma = Mark.objects.get(student=request.user, project=p, question=quest)
            except Mark.DoesNotExist:
                ma = Mark(student=request.user, project=p, question=quest)
            finally:
                ma.result = int(value)
                ma.save()
    return HttpResponseRedirect(reverse('marks:detail', args=(p.id,)))

back/marks/templates/marks/edit.html
{% extends "skel.html" %}

{% block content %}

<form action="{% url 'marks:edit' project.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>

{% endblock  %}

back/marks/templates/marks/index.html
{% extends "skel.html" %}


{% block content %}

<h3><i class="fa fa-angle-right"></i> Projects to rate</h3>
<!-- Rate the groups -->
{% if list %}
{% for project in list %}
<div class="row mt ">
    <div class="col-md-12">
        <div class="form-panel">
            <div class="">
                <h3 class="mb">{{ project.name }}</h3>
                <br>
            </div>
            <div class="panel-body">
                <h4>Description</h4>
                <p>
                    {{ project.description }}
                </p>
                <br>
                <hr>
                <h4>Members</h4>
                <ul class="list-inline">
                    {% for member in project.members.all %}
                    <li><img src="https://cdn.local.epitech.eu/userprofil/trombiview/{{ member.username }}.jpg"><br/>{{ member.username }}</li>
                    {% endfor %}
                </ul>
                <hr>
                {% if not user in project.members.all %}
                    {% if project in projects_rated %}
                    <div class="alert alert-success"><b>Congrats, You have rate this project.</b></div>
                    {% endif %}
                <a href="{% url 'marks:detail' project.id %}">Rate this project <i class="fa fa-share"></i></a>
                {% else %}
                <a href="{% url 'marks:detail' project.id %}">Edit my project <i class="fa fa-share"></i></a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% else %}
<p>No project available.</p>
{% endif %}


{% endblock  %}

back/marks/templates/marks/myprojects.html
{% extends "skel.html" %}


{% block content %}

<h3><i class="fa fa-angle-right"></i> My project(s)</h3>
<!-- Rate the groups -->
{% if my_projects %}
{% for project in my_projects %}
<div class="row mt ">
    <div class="col-md-12">
        <div class="form-panel">
            <div class="">
                <h3 class="mb">{{ project.name }} <a href="{% url 'marks:detail' project.id %}"><i class="fa fa-edit"></i></a></h3>
                <br>
            </div>
            <div class="panel-body">
                <h4>Description</h4>
                <p>
                    {{ project.description }}
                </p>
                <br>
                <hr>
                <h4>Members</h4>
                <ul class="list-inline">
                    {% for member in project.members.all %}
                    <li><img src="https://cdn.local.epitech.eu/userprofil/trombiview/{{ member.username }}.jpg"><br/>{{ member.username }}</li>
                    {% endfor %}
                </ul>
                <hr>
                <a href="{% url 'marks:detail' project.id %}">Edit my project <i class="fa fa-edit"></i></a>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% else %}
<p>No project available.</p>
{% endif %}

{% endblock  %}

back/marks/templates/marks/project.html
{% extends "skel.html" %}

{% block content %}

{% load get_range %}

<h3><i class="fa fa-angle-right"></i> {{ project.name }} </h3>
<div class="row mt ">
    <div class="col-md-12">
        <div class="form-panel">
            <div class="">
                <h3 class="mb">Description</h3>
                <br>
            </div>
            <div class="panel-body">
                {{ project.description|linebreaks }}
            </div>
        </div>
    </div>
</div>
<div class="row mt ">
    <div class="col-md-12">
        <div class="form-panel">
            <div class="">
                <h3 class="mb">Members</h3>
                <br>
            </div>
            <div class="panel-body">
                <ul class="list-inline">
                    {% for member in project.members.all %}
                    <li><img src="https://cdn.local.epitech.eu/userprofil/trombiview/{{ member.username }}.jpg"><br/>{{ member.username }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% if project.pictures.all %}
<div class="row mt ">
    <div class="col-md-12">
        <div class="form-panel">
            <div class="">
                <h3 class="mb">Photos</h3>
                <br>
            </div>
            <div class="panel-body">
                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="3000">
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        {% for picture in project.pictures.all %}
                        <li data-target="#carousel-example-generic" data-slide-to="{{forloop.counter0}}" {% if forloop.counter0 == 0 %} class="active" {% endif %}></li>
                        {% endfor %}
                    </ol>

                    <!-- Wrapper for slides -->
                    <div class="carousel-inner">
                        {% for picture in project.pictures.all %}
                        <div class="item  {% if forloop.counter0 == 0 %}active{% endif %}">
                            <img class="img-responsive center-block" src="/media/{{ picture.file }}" alt="{{ picture.title }}" />
                            <div class="carousel-caption">
                                <h3>{{ picture.title }}</h3>
                            </div>
                        </div>
                        {% endfor %}
                    </div>

                    <!-- Controls -->
                    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                    </a>
                    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    </a>
                </div> <!-- Carousel -->
                </ul>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% if not user in project.members.all %}
<div class="row mt ">
    <div class="col-md-12">
        <div class="form-panel">
            <div class="">
                <h3 class="mb">Mark the project</h3>
                <br>
            </div>
            <div class="panel-body">
                {% if shared_timeslot %}
                {% if entirely_marked %}
                    <div class="alert alert-success"><b>Congrats, You have successfully marked this project.</b></div>
                {% endif %}
                <form action="{% url 'marks:grade' project.id %}" method="post">
                    {% csrf_token %}
                    {% if error_message %}
                    <div class="alert alert-danger"><b>{{ error_message }}</b></div>
                    {% endif %}

                    {% for question, value in questions %}
                    <h4>{{ question.title }}</h4>
                    <p>{{  question.detail }}</p>
                    {% for i in 10|get_range %}
                    {% if not i == 0 and not i = 5 %}
                    <label class="checkbox-inline">
                        <input type="radio" {% if value == i %}checked{% endif %} name="question-{{ question.id }}" value="{{ i }}"> {{ i }}
                    </label>
                    {% endif %}
                    {% endfor %}
                    <hr>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary btn-lg btn-block">Save</button>
                </form>
                {% else %}
                <p class="bg-danger">
                    You are not sharing the same timeslot with this group. So you cannot mark it.
                </p>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="row mt ">
    <div class="col-md-12">
        <div class="form-panel">
            <div class="">
                <h3 class="mb"><i class="fa fa-edit"></i> Edit</h3>
                <br>
            </div>
            <div class="panel-body">
                <form class="form-horizontal style-form" action="{% url 'marks:editsec' project.id %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <form class="form-horizontal">
                        {% if form.errors %}
                        <div class="alert alert-danger">
                            {% for field, error in form.errors.items %}
                            <b>{{ field }} : {{ error }}</b>
                            {% endfor %}
                        </div>
                        {% endif %}
                        <div class="form-group">
                            <label for="inputName" class="col-sm-2 control-label">Name</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="name" id="inputName" value="{{ project.name }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputDescription" class="col-sm-2 control-label">Description</label>
                            <div class="col-sm-10">
                                <textarea rows="10" cols="60" class="form-control" name="description"
                                          id="inputDescription">{{ project.description }}</textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-primary btn-lg btn-block">Save</button>
                            </div>
                        </div>
                    </form>
            </div>
        </div>
    </div>
</div>
<div class="row mt">
    <div class="col-md-12">
        <section class="task-panel tasks-widget">
            <div class="panel-heading">
                <div class=""><h3><i class="fa fa-camera"></i> Manage Photos</h3></div>
                <br>
            </div>
            <div class="panel-body">
                <div class="task-content">
                    {% if project.pictures.all %}
                    <ul class="task-list">
                        {% for pict in project.pictures.all %}
                        <li>
                            <div class="task-title">
                                <span class="task-title-sp"><a href="{{ pict.file.url }}">{{ pict.title }} - {{ pict.file.name }}</a></span>
                                {% if pict.file.width %}
                                <span class="badge bg-info">{{ pict.file.width }} x {{ pict.file.height }} </span>
                                {% endif %}
                                <div class="pull-right hidden-phone">
                                    <a href="{% url 'marks:deleteimg' project.id pict.id %}" class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></a>
                                </div>
                            </div>
                        </li>
                        {% endfor %}

                    </ul>
                    {% else %}
                    <p>No photo(s) yet.</p>
                    {% endif %}
                </div>

                <div class="add-task-row">
                    <form class="form-horizontal style-form" action="{% url 'marks:edit' project.id %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% if form_pict.errors %}
                        <div class="alert alert-danger">
                            {% for field, error in form_pict.errors.items %}
                            <b>{{ field }} : {{ error }}</b>
                            {% endfor %}
                        </div>
                        {% endif %}
                        <div class="form-group">
                            <label for="inputTitle" class="col-sm-2 control-label">Title</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" maxlength="50" name="title" id="inputTitle" placeholder="A title">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputFile" class="col-sm-2 control-label">File</label>
                            <div class="col-sm-10">
                                <input type="file" class="form-control" name="file" id="inputFile">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success btn-lg btn-block">Add New Photo</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </div><!-- /col-md-12-->
</div><!-- /row -->
{% endif %}
{% endblock %}